### ISSUE TITLE
Remove data from pwngrid

### ISSUE THREAD

**Issue by Red-M** [evilsocket/pwngrid#8]
How does someone remove their data from the global pwngrid?

**Comment by evilsocket** [comment]
they ask :D from the unit you want to remove the data of, please send a pwnmail to ca1225b86dc35fef90922d83421d2fc9c824e95b864cfa62da7bea64ffb05aea so that i can verify you actually own the unit ... do you want me to remove from the database everything, including the unit itself, pwnmail messages and reported access points or just the access points?

**Comment by Red-M** [comment]
Done.
Not sure if its the same unit ID as I had to backup and reflash the unit recently.

**Comment by evilsocket** [comment]
if you restored the backup, yes it's the same ... so, do you want me to delete the whole thing? :)

**Comment by Red-M** [comment]
yes please.

**Comment by evilsocket** [comment]
make sure to disable the grid plugin completely, ok?

**Comment by evilsocket** [comment]
messages, access points and the unit account itself have been deleted 👍

**Comment by Red-M** [comment]
I have done so, already. Thank you.
